using System.Collections.Generic;
using System.Text;

namespace Errand.SourceGenerator.Generators.Templates;

/// <summary>
/// Generates the source code for the compile-time dispatcher.
/// </summary>
/// <remarks>
/// <para>
/// The generated class <c>Errand.Generated.ErrandSender</c> implements
/// <c>Errand.Abstractions.IErrandSender</c> using a <c>switch</c>
/// statement that maps each concrete request type to a dedicated dispatch method.
/// This approach is fully reflection-free and Native AOT-compatible.
/// </para>
/// <para>
/// The <c>(ValueTask&lt;TResponse&gt;)(object)</c> double cast inside <c>SendAsync</c> is
/// intentional: it erases the concrete response type at the call site while remaining
/// type-safe because the type system guarantees that <c>TResponse</c> matches the
/// handler's declared response type when the corresponding switch arm is reached.
/// </para>
/// </remarks>
internal static class DispatcherTemplate
{
    // Fully-qualified type aliases used throughout the generated code.
    private const string ValueTaskFq = "global::System.Threading.Tasks.ValueTask";
    private const string CancellationTokenFq = "global::System.Threading.CancellationToken";
    private const string IErrandSenderFq = "global::Errand.Abstractions.IErrandSender";
    private const string IErrandRequestFq = "global::Errand.Abstractions.IErrandRequest";
    private const string MethodImplFq = "global::System.Runtime.CompilerServices.MethodImpl";
    private const string MethodImplOptionsFq = "global::System.Runtime.CompilerServices.MethodImplOptions";

    /// <summary>
    /// Renders the complete source file for the generated <c>ErrandSender</c> class.
    /// </summary>
    /// <param name="handlers">
    /// The validated, conflict-free set of handlers to include in the dispatcher.
    /// May be empty (the generated class will compile but throw at runtime if called).
    /// </param>
    /// <returns>A string containing a valid, self-contained C# source file.</returns>
    public static string Render(IReadOnlyList<HandlerMetadata> handlers)
    {
        var sb = new StringBuilder(capacity: 512 + handlers.Count * 256);

        AppendFileHeader(sb);
        AppendClassOpen(sb);
        AppendSendAsync(sb, handlers);
        AppendDispatchMethods(sb, handlers);
        AppendClassClose(sb);

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // File-level header
    // -------------------------------------------------------------------------

    private static void AppendFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// This file was generated by Errand.SourceGenerator.");
        sb.AppendLine("// Do not modify it manually — changes will be overwritten on the next build.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    // -------------------------------------------------------------------------
    // Class declaration
    // -------------------------------------------------------------------------

    private static void AppendClassOpen(StringBuilder sb)
    {
        sb.AppendLine("namespace Errand.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Compile-time generated, reflection-free implementation of");
        sb.AppendLine($"    /// <see cref=\"{IErrandSenderFq}\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    [global::System.CodeDom.Compiler.GeneratedCode(\"Errand.SourceGenerator\", \"0.1.0\")]");
        sb.AppendLine($"    internal sealed class ErrandSender : {IErrandSenderFq}");
        sb.AppendLine("    {");
    }

    private static void AppendClassClose(StringBuilder sb)
    {
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    // -------------------------------------------------------------------------
    // SendAsync — the main dispatch method
    // -------------------------------------------------------------------------

    private static void AppendSendAsync(StringBuilder sb, IReadOnlyList<HandlerMetadata> handlers)
    {
        sb.AppendLine("        /// <inheritdoc/>");
        sb.AppendLine($"        [{MethodImplFq}({MethodImplOptionsFq}.AggressiveInlining)]");
        sb.AppendLine($"        public {ValueTaskFq}<TResponse> SendAsync<TResponse>(");
        sb.AppendLine($"            {IErrandRequestFq}<TResponse> request,");
        sb.AppendLine($"            {CancellationTokenFq} ct = default)");
        sb.AppendLine("        {");

        if (handlers.Count == 0)
        {
            sb.AppendLine("            throw new global::System.InvalidOperationException(");
            sb.AppendLine("                \"No Errand handlers were found in the compilation. \" +");
            sb.AppendLine("                \"Add classes that implement IErrandHandler<TRequest, TResponse>.\");");
        }
        else
        {
            sb.AppendLine("            switch (request)");
            sb.AppendLine("            {");

            foreach (var handler in handlers)
            {
                var methodName = GetDispatchMethodName(handler);
                sb.AppendLine($"                case {handler.RequestFullName} r:");
                sb.AppendLine($"                    return ({ValueTaskFq}<TResponse>)(object)");
                sb.AppendLine($"                        {methodName}(r, ct);");
            }

            sb.AppendLine("                default:");
            sb.AppendLine("                    throw new global::System.InvalidOperationException(");
            sb.AppendLine("                        $\"No handler registered for request type '{{request.GetType().FullName}}'.\");");
            sb.AppendLine("            }");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    // -------------------------------------------------------------------------
    // Per-handler dispatch methods
    // -------------------------------------------------------------------------

    private static void AppendDispatchMethods(StringBuilder sb, IReadOnlyList<HandlerMetadata> handlers)
    {
        foreach (var handler in handlers)
        {
            var methodName = GetDispatchMethodName(handler);

            sb.AppendLine($"        [{MethodImplFq}({MethodImplOptionsFq}.AggressiveInlining)]");
            sb.AppendLine($"        private static {ValueTaskFq}<{handler.ResponseFullName}>");
            sb.AppendLine($"            {methodName}(");
            sb.AppendLine($"                {handler.RequestFullName} request,");
            sb.AppendLine($"                {CancellationTokenFq} ct)");
            sb.AppendLine($"            => new {handler.HandlerFullName}().HandleAsync(request, ct);");
            sb.AppendLine();
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Derives a unique, valid C# identifier for the per-handler dispatch method
    /// from the request type's fully-qualified name.
    /// </summary>
    /// <example>
    /// <c>global::MyApp.Orders.CreateOrderRequest</c>
    /// → <c>Dispatch_MyApp_Orders_CreateOrderRequest</c>
    /// </example>
    internal static string GetDispatchMethodName(HandlerMetadata handler)
    {
        // Strip "global::" then replace namespace separators and generic characters
        // with underscores to produce a valid C# identifier.
        var sanitized = handler.RequestFullName
            .Replace("global::", string.Empty)
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", string.Empty)
            .Replace(",", "_")
            .Replace(" ", string.Empty);

        return "Dispatch_" + sanitized;
    }
}
